### ISSUE TITLE
Links to pictures are broken

### ISSUE THREAD

**Issue by KN4USA** [rfrht/FT-991A#1]
Can not open the links to pictures for the explanation of power settings.

**Comment by rfrht** [comment]
Hello there,

I have a construction undergoing at home - and will take a while to complete

So the images won't load for the next 45 days :-{

**Comment by rfrht** [comment]
> Hello there,
> 
> I have a construction undergoing at home - and will take a while to complete
> 
> So the images won't load for the next 45 days :-{

Well, **i wish** it was next 45 days - Fingers crossed to be back home by December :-P

**Comment by rfrht** [comment]
> Can not open the links to pictures for the explanation of power settings.

Hello @KN4USA 

I have **just** brought the server back online, after *long* months!

Apologies for the inconvenience!
