### ISSUE TITLE
Info on setups for FT-8/4 and VARA-HF?

### ISSUE THREAD

**Issue by DJenner8** [rfrht/FT-991A#3]
Do you have any information on setting up the FT-991A for FT-8/4 (WSJT-X) and/or for setting up VARA HF?

**Comment by rfrht** [comment]
Hello there, DJenner! Thanks for writing.

I don't use WSJT-X for FT8 (i like MSHV more) and I have concerns on the Vara thing as this is a closed source tool. Thus I don't have any material in these software.

Sorry for not being able to be of more help.

All the best for you;

- RF.

**Comment by DJenner8** [comment]
Thanks for responding.  Your FT-991A github is a treasure!

What do you like more about MSHV?   I had not heard of it.

73,
Dave
K7DCJ

**Comment by rfrht** [comment]
Hello, Dave! Thank you very much for your kind words.

> What do you like more about MSHV? I had not heard of it.

Well, I found the original WSJT a bit convoluted on setting up the transmission, split mode, etc. But I really think that this boils down to MSHV being the first FT8 software that I was exposed and then I got attached to it ;-)

All the best for you.
