### ISSUE TITLE
Fans at reduced power

### ISSUE THREAD

**Issue by ChrisK9EQ** [rfrht/FT-991A#4]
Outstanding resource for FT-991A owners! Thanks!

Regarding fans, I have noticed a problem with some fans when they are not run at the specified voltage. In other words, running the fan at a lower speed to reduce noise, power, and/or air flow. They seem to fail prematurely. My guess is that when the fan turns at a lower speed for long periods, the lubricant does not properly cover the bearings. In the case of the fluidic bearings, the rotating shaft may "crash" and cause excessive wear. I've seen 70,000 hr fans start to get very noisy within a year under these conditions. (In my case the system operated 24/7/365.) 

Unfortunately many of the fans do not discuss operation at an operating point below that which is specified, which it looks like the FT-991A does. Their MTBF specification is for rated conditions only.

Fans and batteries will humble the greatest engineer!

73,
Chris, K9EQ
HamOperator.com

**Comment by rfrht** [comment]
Nice post, Chris! Thanks for sharing!
